### ISSUE TITLE
Does not support .NET 5: System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by Grauenwolf** [SavantBuffer/DbConnector#2]
Message: 
    Test method Recipes.DbConnector.Joins.JoinsTests.FindByEmployeeClassificationKey threw exception: 
    System.TypeInitializationException: The type initializer for 'DbConnector.Core.DynamicColumnMapper' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
  Stack Trace: 
    RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    Type.GetMethod(String name, BindingFlags bindingAttr)
    Type.GetMethod(String name)
    DynamicColumnMapper.cctor()

**Comment by treborgero** [comment]
@Grauenwolf Thank you. I'll get to work on it this upcoming week. I'm worried Microsoft might've introduced other bugs even though .NET 5 implements .NET Standard 2.1. I'll also merge your [Pull Request](https://github.com/SavantBuffer/DbConnector/pull/3). Happy coding!

**Comment by treborgero** [comment]
@Grauenwolf Thank you again! Issue is now fixed.
